Handle a case when there is no buy/sell returned from Kucoin for some market/symbol
BananaCoding/ExchangeSharp pull request #4
Opened 2018-05-10 12:07 UTC by piangsit

Handle a case when there is no buy/sell returned from Kucoin for some market/symbol

2018-05-14 06:48 UTC, Jirapong requested changes

2018-05-14 06:48 UTC, Jirapong commented on ExchangeSharp/API/Exchanges/ExchangeKucoinAPI.cs
> +                    Ask = token["sell"] == null ? 0 : token["sell"].Value<decimal>(),
Wonder if we can shorten a syntax to Ask = (decimal) token["sell"] ?? 0;

2018-05-15 12:39 UTC, piangsit commented
Fixed. Need to convert decimal to be nullable value for using with ??

2018-05-16 08:10 UTC, Jirapong approved these changes

2018-05-16 08:10 UTC, merged